package tn.esprit.CRM.gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;

public class DirecteurController {
	@FXML
	private Button manage;
	@FXML
	private Button conge;
	@FXML
	private Button salary;
	@FXML
	private Button staff;

	// Event Listener on Button[#manage].onAction
	@FXML
	public void manage(ActionEvent event) throws IOException {
		FXMLLoader loaders= new FXMLLoader(getClass().getResource("./Ajout.fxml"));
	       Parent root;
	  	 	root=loaders.load();
	  	 	manage.getScene().setRoot(root);
	}
	// Event Listener on Button[#conge].onAction
	@FXML
	public void conge(ActionEvent event) throws IOException {
		FXMLLoader loaders= new FXMLLoader(getClass().getResource("./TraitementConge.fxml"));
	       Parent root;
	  	 	root=loaders.load();
	  	 	manage.getScene().setRoot(root);
	}
	// Event Listener on Button[#salary].onAction
	@FXML
	public void salary(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#staff].onAction
	@FXML
	public void staff(ActionEvent event) throws IOException {
		FXMLLoader loaders= new FXMLLoader(getClass().getResource("./AfficherStaff.fxml"));
	       Parent root;
	  	 	root=loaders.load();
	  	 	manage.getScene().setRoot(root);
	}
}
