package tn.esprit.CRM.gui;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.sql.Date;
import java.util.List;
import java.util.ResourceBundle;

import javax.naming.InitialContext;
import javax.naming.NamingException;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import tn.esprit.CRM.persistence.Conge;
import tn.esprit.CRM.services.StaffServiceRemote;
import javafx.scene.control.TableColumn;

public class CongeAffController implements Initializable{
	@FXML
	private TableView<Conge> table;
	@FXML
	private TableColumn<Conge,Date> date;
	@FXML
	private TableColumn<Conge,String> type;
	@FXML
	private TableColumn<Conge,Integer> days;
	@FXML
	private TableColumn<Conge,String> certif;
	@FXML
	private TableColumn<Conge,String> status;
	@FXML
	private Button traiter;
	@FXML
	private Button re;

	// Event Listener on Button[#traiter].onAction
	@FXML
	public void traiter(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#re].onAction
	@FXML
	public void re(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		InitialContext ctx;
		try {
			ctx = new InitialContext();
			StaffServiceRemote proxy;

			proxy = (StaffServiceRemote) ctx.lookup("CRM-ear/CRM-ejb/StaffService!tn.esprit.CRM.services.StaffServiceRemote");
			
			ObservableList<Conge> data = FXCollections.observableArrayList(proxy.FindAllDemandeConge());	
				List<Conge> li= proxy.FindAllDemandeConge();
			for(Conge c:li){
				if(c.getStatus_co().equals("not examined yet")){
					
				}
				System.out.println(c);
			}

			table.setItems(data);
			date.setCellValueFactory(new PropertyValueFactory<Conge,Date>("date_co"));
			type.setCellValueFactory(new PropertyValueFactory<Conge,String>("type_co"));
			certif.setCellValueFactory(new PropertyValueFactory<Conge,String>("certificat"));
			days.setCellValueFactory(new PropertyValueFactory<Conge,Integer>("nbjrs_co"));
			status.setCellValueFactory(new PropertyValueFactory<Conge,String>("status_co"));
		
		
			
			
		} catch (NamingException e1) {
			// TODO Auto-generated catch blocks
			//e1.printStackTrace();
		}
		
	
		
	}
}
