package tn.esprit.CRM.gui;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.layout.HBox;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.VBox;

import javafx.scene.layout.Pane;

public class HomeController implements Initializable{
	@FXML
	private Button btnOverview;
	@FXML
	private Button btnOrders;
	@FXML
	private Button btnCustomers;
	@FXML
	private Button btnMenus;
	@FXML
	private Button btnPackages;
	@FXML
	private Button btnSettings;
	@FXML
	private Button btnSignout;
	@FXML
	private Pane pnlCustomer;
	@FXML
	private Pane pnlOrders;
	@FXML
	private Pane pnlMenus;
	@FXML
	private Pane pnlOverview;
	@FXML
	private Label nbrestaff;
	@FXML
	private Label nbrdispo;
	@FXML
	private Label nbrnondispo;
	@FXML
	private Label nbrconge;
	@FXML
	private VBox pnItems;
	@FXML
	private HBox itemC;
	@FXML
	private Label item1;
	@FXML
	private Label item2;
	@FXML
	private Label item3;
	@FXML
	private Label item4;
	@FXML
	private Button dispo;

	// Event Listener on Button[#btnOverview].onAction
	@FXML
	public void handleClicks1(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnOrders].onAction
	@FXML
	public void handleClicks2(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCustomers].onAction
	@FXML
	public void handleClicks3(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnMenus].onAction
	@FXML
	public void handleClicks4(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnPackages].onAction
	@FXML
	public void btnPackages(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSettings].onAction
	@FXML
	public void bouton2(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSignout].onAction
	@FXML
	public void bouton3(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
	}
}
