package tn.esprit.CRM.gui;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.layout.HBox;

import javafx.event.ActionEvent;

public class ItemController {
	@FXML
	private HBox itemC;
	@FXML
	private Button show;

	// Event Listener on Button[#show].onAction
	@FXML
	public void show(ActionEvent event) {
		// TODO Autogenerated
	}
}
